### ISSUE TITLE
Project One Framework Discussion and Selection [12/7]

### ISSUE THREAD

**Issue by majway27** [BeerLiftersAssociation/design#1]
Team propose and discuss language frameworks.

- Based on results of: https://github.com/BeerLiftersAssociation/project_one/issues/3
  - Choose language frameworks

Target 12/7

**Comment by majway27** [comment]
My preference would be Python for backend development, and Angular for a front-end framework.

I have an older project that I used Angular in, and we would get off the ground faster by having that reference.

Alternatively, I am interested in learning React.  If we went that direction we'd pick up some drag around tool immersion and familiarization.

Please let me know your preferences and thoughts.  @vedran3 @JBluesify

**Comment by vedran3** [comment]
I like the idea of using Python for backend development but I don't have a strong preference on Angular vs React. I see that React is more of a newer standard in development so I would support your interest in learning React, but I am ok with either choice.

**Comment by majway27** [comment]
Let's go with Python/React and see how React treats us.
